version: '3.3'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - metabase/config/postgres_exemple.env

  # app:
  #   build: .
  #   depends_on:
  #   - postgres

  metabase:
    image: metabase/metabase
    ports:
      - 3002:3000
    depends_on:
      - postgres