name: Documentation

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Sphinx documentation
      run: |
      cd docs/
      sphinx-apidoc -f -o . ../src/
      make html