name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalando dependências
      run: |
        pip install sphinx==5.3.0

    # - name: Build Sphinx 
    #   run: |
    #     sphinx-build -W -b html /docs _build

    - name: Run sphinx
      working-directory: ./docs
      run: |
        make html
    # - name: Upload de documentação
    #   if: always()
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: documentation
    #     path: _build

