name: Poetry

on: [push]

jobs:
  poetry:
  runs-on: ubuntu-latest
  steps:
  - name: Instalando Poetry
      run: |
      python -m pip install poetry

  - name: Instalando dependencias
    run: |
      poetry install

  - name: Verificando lint
    run: |
      pip install pylint
      pylint src
    continue-on-error: true

  - name: Realizando testes
    run: |
      poetry run pytest --cov 

  - name: Incrementando versão na lib
    run: |
      poetry version patch

  - name: Build package
    run: |
      poetry build -v

  - name: Publicação no PyPI
    run: |
      poetry config pypi-token.pypi ${{ token }}
      poetry publish --username __token__ -v