name: Poetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Confugurando Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalando Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

    - name: Configurando Poetry
      run: |
        echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $GITHUB_SHELL

    - name: Instalando dependencias
      run: |
        poetry install

    - name: Testando com Pytest
      run: |
        poetry run pytest
