name: Poetry

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Confugurando Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalando Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    # - name: Configurando Poetry
    #   run: |
    #     echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $GITHUB_SHELL

    # - name: Testando com Pytest
    #   run: |
    #     poetry run pytest
    - name: Executando
      run: docker-compose up -d
